### ISSUE TITLE
Roadmap/umbrella for 6.x.x

### ISSUE THREAD

**Issue by drcmda** [drcmda/react-spring#212]
Ideas welcome! For now:

- [x] Leaner api
- [x] Leaner/faster spring implementation
- [x] Moving delay back into config
- [x] Transitions can trail
- [x] Trails can take durations
- [x] Trails can reverse direction (start trailing from top/bottom for instance)
- [x] Keyframe overhaul
- [x] Move parallax into addons
- [x] Allow to/enter/leave/update to receive arrays, for chained/multistage animations
- [x] Rewrite the spring updater, remove setTimeout and use *one* RAF instead of many for each individual animated value
- [x] Treeshaking & shaking off weight in general
- [ ] Move away from animated?

### Leaner/faster spring implementation

SSE looks far leaner (and faster) to me than RK4 just by judging the code. When i read that many game engines use SSE for that reason i am thinking maybe react-spring should, too.

https://gafferongames.com/post/integration_basics/#semi-implicit-euler

### Moving delay back into config

This was a mistake. Moving it out effectively made duration chaining impossible, where otherwise every animation value can be given its own config.

### Keyframe overhaul

 The current api is still too complex and unwieldy. 

### Treeshaking & shaking off weight in general

@Andarist and @TrySound had some great ideas here that should be realized.

### Move away from animated?

Animateds overall structure is a given because of interpolation. It doesn't know what interpolates from what before rendering and figures it out runtime. I believe that makes for most of the structural decisions. In a declarative world we can know precisely which interpolator interpolates from which parent interpolator and so on. So *maybe* it could be a good idea to move away from animated eventually and write a leaner foundation more suitable for declarative purposes. This would be the end for the imperative api we still offer, though.

### Move parallax out of this lib?

Mixed thoughts about this one. If it were an add-on or a lib with a dependency on RS, then we would be closer to do-one-thing-well ideals.

**Comment by jbovenschen** [comment]
First of all thank you for all the effort you put into this library.

I mostly am (surprised?) by "Move away from animated?".  What I am curious about is is your opinion of [reanimated](https://github.com/kmagiera/react-native-reanimated). Is it an idea to use this library instead of the `animated` library? 

It would solve the following issues you did point out;
* More declarative API for writing animations.
* Possibility to add another spring implementation
* Ability to add your own interpolators.
* The native implementation would run all 'native'.

What I am curious about is the following;
"It doesn't know what interpolates from what before rendering and figures it out runtime" What do you mean by this exactly would you like to pre generate the whole animation before it runs?

**Comment by drcmda** [comment]
I think all those points are already fulfilled right now. react-spring is 100% declarative, you can exchange spring implementations fully ([with the impl prop](https://github.com/drcmda/react-spring#timeduration-based-implementations-and-addons-demo)), you can run your own interpolators, and "native" is dependent on the target but it usually means outside of react most of the time.

The problem with animated is the complex parent-child interaction. You can have a value that animates into an interpolator, which drives another and another and another ... but it can't know the full graph (because it functions imperative) and therefore calculates, which costs time. I've already optimized it here, but the whole structural overhead probably isn't warranted. I think i could cut the libs size in half if the foundation is rewritten.

**Comment by jlarmstrongiv** [comment]
Might as well throw in my two cents 😉 

I do like having parallax in the library.  I understand the do-one-thing-well approach, but I think parallax is an important part of an animation library.  

I‘m all for a leaner API.  I think an up-to-date and comprehensive documentation that is all in one place would be a nice priority too 😄

**Comment by montogeek** [comment]
I should help you updating all demos to latest version, will try to find some space this week.

**Comment by drcmda** [comment]
New branch: https://github.com/drcmda/react-spring/tree/6.x is almost functional

**Comment by rxb** [comment]
If animated does stick around, it would be great to use useNativeDriver where possible for React Native

**Comment by iammarkps** [comment]
IMO, Multiple packages within this repo is very good ideas.
